on:
  workflow_dispatch:
  push:
    branches: [master]

jobs:
    package:
      name: build and run unit tests
      runs-on: amd64

      steps:

        - uses: actions/checkout@v4
          with:
            persist-credentials: false

        - name: "Launch earthly"
          run: earthly +check
